version: 2

jobs:
  build:
    machine: true
    working_directory: ~/python-flask-docker-hello-world
    steps:
      - checkout
      - run:
          name: Login to Docker
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
      - run:
          name: Build Hello
          command: docker build -t flask-hello hello/
      - run:
          name: Build World
          command: docker build -t flask-world world/
      - run:
          name: Tag Hello image
          command: docker tag flask-hello crowdflux/python-hello:${CIRCLE_TAG}
      - run:
          name: Tag World image
          command: docker tag flask-world crowdflux/python-world:${CIRCLE_TAG}
      - run:
          name: Push Hello Image
          command: docker push crowdflux/python-hello
      - run:
          name: Push World Image
          command: docker push crowdflux/python-world

workflows:
  version: 2
  migrations-build:
    jobs:
      - build:
          context: Docker-Repository
          filters:
              tags:
                  only: /v.*/
              branches:
                  ignore: /.*/

